[package]
name = "editor"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
autocxx = "0.30.0"
cxx = "1.0.158"

[build-dependencies]
autocxx-build = "0.30.0"
bindgen = "0.71.1"

[package.metadata.bundle]
identifier = "com.simulo.editor"
resources = ["default.metallib"]
