name: Build on Linux
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl xxd libopencv-dev libx11-dev libxkbcommon-dev wayland-protocols libvulkan-dev build-essential cmake
          version: "1.0"

      - name: Download ONNX Runtime
        run: |
          mkdir -p extern/onnxruntime
          curl -L https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-linux-x64-1.22.0.tgz -o onnxruntime-linux-x64-1.22.0.tgz
          tar -xzf onnxruntime-linux-x64-1.22.0.tgz -C extern/onnxruntime --strip-components=1

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install -DONNXRuntime_DIR=${{ github.workspace }}/extern/onnxruntime/lib/cmake/onnxruntime

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build

      - name: Install project
        run: cmake --install build --config Release

      - name: Upload install artifact
        uses: actions/upload-artifact@v4
        with:
          path: install
